# Configuration file for the Companion AI assistant

model:
  path: "models/DeepSeek-R1-Distill-Qwen-7B-Q8_0.gguf"  # Default model path
  temperature: 0.7  # Controls randomness (0 = deterministic, 1 = highly random)
  max_tokens: 64000  # Maximum number of tokens in generated responses
  top_p: 0.9  # Nucleus sampling for diversity
  n_ctx: 128000  # Context window size
  n_gpu_layers: 20  # Number of layers to run on GPU (for acceleration)